#!/bin/bash

set -e

cwd="$(realpath ${BASH_SOURCE%/*})"
packages=$(realpath "$cwd/packages")

aur sync --remove --pacman-conf $cwd/pacman.conf --sign --chroot $@

echo "Synchronizing packages"
rsync --delete --info=progress2 --copy-links --recursive $packages/ archeron.rded.nl:/var/www/arch.rded.nl/
